fix kustvakt ldap pass forwarding

diff --git a/charts/korap/templates/kustvakt-full-deployment.yaml b/charts/korap/templates/kustvakt-full-deployment.yaml
--- a/charts/korap/templates/kustvakt-full-deployment.yaml
+++ b/charts/korap/templates/kustvakt-full-deployment.yaml
@@ -24,6 +24,46 @@ spec:
       {{- end }}
       serviceAccountName: {{ include "korap.fullname" . }}
       restartPolicy: {{ .Values.restartPolicy | default "Always" }}
+
+      {{- if and (.Values.full | default dict).enabled (.Values.full.kustvaktLdap.enabled) }}
+      initContainers:
+        - name: build-ldap-conf
+          image: busybox:1.36
+          command:
+            - sh
+            - -ce
+            - |
+              set -eu
+              PW_FILE="/kustvakt/ldap/secret/{{ .Values.full.kustvaktLdap.passwordKey }}"
+              TPL="/kustvakt/ldap-template/ldap.conf.template"
+              OUT="/work-ldap/ldap.conf"
+              if [ ! -s "$PW_FILE" ]; then
+                echo "Password file not found: $PW_FILE" >&2
+                exit 1
+              fi
+              PW="$(cat "$PW_FILE")"
+              if [ -z "$PW" ]; then
+                echo "Password is empty!" >&2
+                exit 1
+              fi
+              if [ ! -s "$TPL" ]; then
+                echo "Template not found: $TPL" >&2
+                exit 1
+              fi
+              sed "s|__LDAP_PASSWORD__|${PW//|/\\|}|g" "$TPL" > "$OUT"
+              chmod 600 "$OUT"
+              echo "Rendered ldap.conf to $OUT"
+          volumeMounts:
+            - name: kustvakt-ldap-config     # ConfigMap with template
+              mountPath: /kustvakt/ldap-template
+              readOnly: true
+            - name: kustvakt-ldap-secret     # Secret with password file
+              mountPath: /kustvakt/ldap/secret
+              readOnly: true
+            - name: kustvakt-ldap-generated  # EmptyDir for final ldap.conf
+              mountPath: /work-ldap
+      {{- end }}
+
       containers:
         - name: kustvakt-full
           image: "{{ (.Values.kustvaktFull | default dict).image }}"
@@ -40,13 +80,6 @@ spec:
             {{- if and (.Values.full | default dict).enabled (.Values.full.kustvaktLdap.enabled) }}
             - name: KUSTVAKT_LDAP_CONF
               value: "/kustvakt/ldap/ldap.conf"
-
-            # *** REQUIRED FIX ***
-            - name: KUSTVAKT_LDAP_PASSWORD
-              valueFrom:
-                secretKeyRef:
-                  name: {{ .Values.full.kustvaktLdap.passwordSecret }}
-                  key: {{ .Values.full.kustvaktLdap.passwordKey }}
             {{- end }}
 
           volumeMounts:
@@ -59,16 +92,16 @@ spec:
             {{- end }}
 
             {{- if and (.Values.full | default dict).enabled (.Values.full.kustvaktLdap.enabled) }}
-            - name: kustvakt-ldap-config
+            # Mount the generated ldap.conf instead of the raw ConfigMap
+            - name: kustvakt-ldap-generated
               mountPath: /kustvakt/ldap
-              readOnly: true
-
+            # Keep secret mounted (some setups also use trustStore here)
             - name: kustvakt-ldap-secret
               mountPath: /kustvakt/ldap/secret
               readOnly: true
             {{- end }}
 
-            {{- /* super_client_info override */ -}}
+            {{- /* super_client_info override into data dir to take precedence */ -}}
             {{- $scSecret := (.Values.full | default dict).superClientInfoSecretName }}
             {{- if not $scSecret }}
             {{- if and (.Values.full | default dict).enabled ((.Values.full | default dict).superClientInfo | default dict).enabled }}
@@ -97,10 +130,14 @@ spec:
         - name: kustvakt-ldap-config
           configMap:
             name: {{ include "korap.fullname" . }}-kustvakt-ldap-config
-
+            items:
+              - key: ldap.conf.template
+                path: ldap.conf.template
         - name: kustvakt-ldap-secret
           secret:
-            secretName: {{ .Values.full.kustvaktLdap.passwordSecret }}
+            secretName: {{ ternary .Values.full.kustvaktLdap.passwordSecret (printf "%s-kustvakt-ldap-secret" (include "korap.fullname" .)) (hasKey .Values.full.kustvaktLdap "passwordSecret") }}
+        - name: kustvakt-ldap-generated
+          emptyDir: {}
         {{- end }}
 
         {{- if $scSecret }}
@@ -108,7 +145,6 @@ spec:
           secret:
             secretName: {{ $scSecret }}
         {{- end }}
-
 ---
 apiVersion: v1
 kind: Service
